services:

  virtuoso:
    container_name: virtuoso
    image: openlink/virtuoso-opensource-7
    secrets:
      - dba_password
    command: >
      sh -c "
      export DBA_PASSWORD=$(cat /run/secrets/dba_password);
      exec /virtuoso-entrypoint.sh
      "
    environment:
      - VIRT_DATABASE_ERRORLOGLEVEL=3
      - VIRT_SPARQL_DEFAULTGRAPH=${VIRT_SPARQL_DEFAULTGRAPH}
      - VIRT_SPARQL_DEFAULTQUERY=SELECT DISTINCT * FROM <${VIRT_SPARQL_DEFAULTGRAPH}> WHERE { ?s ?p ?o } LIMIT 100
      - VIRT_PARAMETERS_DIRSALLOWED=., /usr/local/virtuoso-opensource/share/virtuoso/vad, /rdf
      - VIRT_PLUGINS_-=-
      # performance tuning
      - VIRT_NumberOfBuffers=170000
      - VIRT_MaxDirtyBuffers=130000
      - VIRT_CheckpointInterval=60
    volumes:
      - ./rdf:/rdf
      - ./initdb.d:/opt/virtuoso-opensource/initdb.d
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8890:8890"
      - "1111:1111"
    restart: unless-stopped

  watcher:
    container_name: watcher
    build: ./inotify
    image: watcher
    secrets:
      - dba_password

    environment:
      - VIRT_SPARQL_DEFAULTGRAPH=${VIRT_SPARQL_DEFAULTGRAPH}
    volumes:
      - ./rdf:/rdf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - virtuoso
    restart: unless-stopped

secrets:
  dba_password:
    file: ./secrets/dba_password.txt

